title: JayKanidan
subtitle: Knowing enough to think you are right but not knowing enough to know you are wrong
description: >- # this means to ignore newlines until "baseurl:"
  Logging my life events.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    # - text: Blog
    #   url: /blog
    # - text: Gallery
    #   url: /gallery
    # - text: Shop
    #   url : /shop
    # - text: Contact Me
    #   url : /contact
    # - text: Styleguide
    #   url: /styleguide
    # - text: Get Started
    #   url: /get-started
    - text: AnImation
      url : /animation
    - text: Entertainment
      url : /entertainment
    - text: AI
      url : /ai
    - text: Stories
      url : /stories

# Edit these details

author_logo: profile.png
author: Nitthilan, Kannappan Jayakodi
author_bio: Hi, my name is Nitthilan. K. J. Pursuing PhD (ML/AI) @ Washington State University. My general research interests are at the intersection of Machine Learning (ML) and Computing Systems (Sys). Specifically, I'm working towards the vision of  EdgeAI to efficiently deploy AI solutions for emerging applications (e.g., robotics, self-driving cars, augmented/virtual reality, and smart health) on edge platforms that are constrained by resources (power, compute, and memory). (a) Developed a novel hardware-aware design and optimization framework to trade-off power, performance, and accuracy for performing inference using deep neural networks. (b) Studied effective instantiations of this framework for different applications - Convolutional neural networks for image classification, Graph convolutional networks for 3D computer vision, and Generative adversarial networks for image manipulation tasks.(c) Published papers at top-tier venues including three journal papers (ACM/IEEE Transactions on CAD and Embedded Computing Systems) and three conference papers (DAC, DATE, AAAI). Three papers under review at ICPR, TCAD and JAIR. (d) Interested in Artificial General Intelligence (AGI), Deep Generative Models (GAN, VQVAE) in VFX/Graphics
author_email: "nitthilan@gmail.com"
author_location: Pullman, WA, USA.
author_website_url: "http://nitthilan.github.io"
typewrite-text: Checkout the colors generated with this prism

author_work_experiences:
            - company_name: Polycom
              company_logo: polycom.svg
              company_url: https://www.poly.com/us/en
              designation: Senior Staff Engineer
              description: Cloud Video Conferencing Platform Projects
              visibility: true
            - company_name: Ittiam Systems
              company_logo: ittiam.png
              company_url: https://www.ittiam.com/
              designation: Senior Engineer
              description: End-to-end Video Codecs - H264, MPEG4/2
              visibility: true

author_education_details:
              - college_logo: wsu.svg
                college_name: Washington State University
                college_url: https://wsu.edu/
                college_degree: PhD 
                description: Artificial Intelligence and Machine Learning
                visibility: true

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: false
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: false

# social links
twitter_username: nitthilan
github_username:  nitthilan
facebook_username: nitthilan
linkedin_username: nitthilan
# behance_username: johndoe
instagram_username: nitthilan
# medium_username: johndoe
telegram_username: nitthilan
# dribbble_username: johndoe
flickr_username: nitthilan

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
# wakatime_username: nitthilan

# mailchimp embedded form url (newsletter):
mailchimp_form_url: http://eepurl.com/hdS66T 
#https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: nitthilan@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-178463631-1

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
